services:
  messenger-gateway-dev:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - messenger-service-dev
    networks:
      - messenger-network-dev
    deploy:
      restart_policy:
        condition: on-failure

  messenger-service-dev:
    image: messenger-service:${IMAGE_TAG}
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - messenger-network

  messenger-redis-dev:
    image: redis:alpine
    networks:
      - messenger-network-dev

  messenger-postgres-dev:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: messenger
    volumes:
      - messenger-postgres-data-dev:/var/lib/postgresql/data
    networks:
      - messenger-network-dev

networks:
  messenger-network-dev:
    driver: bridge
    attachable: true

volumes:
  messenger-postgres-data-dev:
