version: "3.9"

services:
  messenger-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - messenger-service
    networks:
      - messenger-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  messenger-service:
    image: messenger-service:${IMAGE_TAG}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - messenger-network

  messenger-redis:
    image: redis:alpine
    deploy:
      replicas: 1
    networks:
      - messenger-network

  messenger-postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: messenger
    volumes:
      - messenger-postgres-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
    networks:
      - messenger-network

networks:
  messenger-network:
    driver: overlay
    attachable: true

volumes:
  messenger-postgres-data:
